### ISSUE TITLE
Support auth via arbitrary HTTP headers

### ISSUE THREAD

**Issue by HolySamosa** [FraunhoferIOSB/FROST-Manager#1]
We are using a Kong API Gateway to provide auth for our STA instance, which accepts an api token via an HTTP header of `apikey`.  So unfortunately, we can'y currently make use of FROST-Manager.

May I request support for auth schemes based on arbitrary HTTP headers?

(Hijacking my own thread here, but I'm curious- are there any other projects that provide a UI for creating / editing entities in an STA instance?)

Thanks!

**Comment by hylkevds** [comment]
That's pretty easy to do. I've added an auth method called AuthHeader that allows you to set an arbitrary header.
Using [AuthHeader.java](https://github.com/FraunhoferIOSB/FROST-Manager/blob/master/src/main/java/de/fraunhofer/iosb/ilt/sensorthingsmanager/auth/AuthHeader.java) as an example you can also implement more complex mechanisms.
If you drop a class that implements `AuthMethod` in the classpath, it will automatically be picked up and added to the auth drop-down.
